name: Deploy python with poetry
description: Build & deploy python package using poetry

inputs:
  pypi-token:
    description: Token to access pypi.org
    required: true



runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Prepare Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "POETRY_VIRTUALENVS_CREATE=false" >> $GITHUB_ENV
        poetry install
    
    - name: Deploy & Publish
      shell: bash
      run: poetry publish --skip-existing --build -u __token__ -p ${{ inputs.pypi_token }}
